-- Sample flights across every status. All times are relative to LOCALTIMESTAMP
-- so the dataset never goes stale.
INSERT INTO flights (flight_number, origin, destination, departure_time, arrival_time, status) VALUES
    ('BA117',  'LHR', 'JFK', DATEADD('HOUR',   6, LOCALTIMESTAMP), DATEADD('HOUR',  14, LOCALTIMESTAMP), 'SCHEDULED'),
    ('LH400',  'FRA', 'JFK', DATEADD('HOUR',  20, LOCALTIMESTAMP), DATEADD('HOUR',  29, LOCALTIMESTAMP), 'SCHEDULED'),
    ('AF006',  'CDG', 'JFK', DATEADD('DAY',    2, LOCALTIMESTAMP), DATEADD('HOUR',  56, LOCALTIMESTAMP), 'SCHEDULED'),
    ('UA901',  'SFO', 'LHR', DATEADD('HOUR',   3, LOCALTIMESTAMP), DATEADD('HOUR',  13, LOCALTIMESTAMP), 'DELAYED'),
    ('KL641',  'AMS', 'JFK', DATEADD('HOUR',   5, LOCALTIMESTAMP), DATEADD('HOUR',  13, LOCALTIMESTAMP), 'DELAYED'),
    ('DL44',   'JFK', 'LAX', DATEADD('MINUTE', -15, LOCALTIMESTAMP), DATEADD('HOUR', 5, LOCALTIMESTAMP), 'DEPARTED'),
    ('EK202',  'DXB', 'JFK', DATEADD('HOUR',  -4, LOCALTIMESTAMP), DATEADD('HOUR',   9, LOCALTIMESTAMP), 'IN_AIR'),
    ('QF1',    'SYD', 'LHR', DATEADD('HOUR', -10, LOCALTIMESTAMP), DATEADD('HOUR',  12, LOCALTIMESTAMP), 'IN_AIR'),
    ('AA100',  'JFK', 'LHR', DATEADD('HOUR', -12, LOCALTIMESTAMP), DATEADD('HOUR',  -5, LOCALTIMESTAMP), 'LANDED'),
    ('SQ25',   'SIN', 'FRA', DATEADD('HOUR', -16, LOCALTIMESTAMP), DATEADD('HOUR',  -3, LOCALTIMESTAMP), 'LANDED'),
    ('IB6251', 'MAD', 'JFK', DATEADD('HOUR',   8, LOCALTIMESTAMP), DATEADD('HOUR',  16, LOCALTIMESTAMP), 'CANCELLED');
