CREATE TABLE flights (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_number  VARCHAR(10)  NOT NULL,
    origin         VARCHAR(3)   NOT NULL,
    destination    VARCHAR(3)   NOT NULL,
    departure_time TIMESTAMP    NOT NULL,
    arrival_time   TIMESTAMP    NOT NULL,
    status         VARCHAR(20)  NOT NULL DEFAULT 'SCHEDULED',
    created_at     TIMESTAMP    NOT NULL DEFAULT LOCALTIMESTAMP,
    updated_at     TIMESTAMP    NOT NULL DEFAULT LOCALTIMESTAMP,
    CONSTRAINT uk_flights_flight_number UNIQUE (flight_number),
    CONSTRAINT ck_flights_status CHECK (status IN ('SCHEDULED', 'DELAYED', 'DEPARTED', 'IN_AIR', 'LANDED', 'CANCELLED'))
);
